### ISSUE TITLE
Commit kustomized "deploy.yml" for easy deployment

### ISSUE THREAD

**Issue by moshloop** [flanksource/platform-operator#15]

**Comment by mazzy89** [comment]
The idea here is to generate out of all the `kustomize` config a unique YAML and deploy all the configuration easily.

As discussed the generated resources will be deployed in a dedicated namespace named `flanksource-system`.

**Comment by mazzy89** [comment]
THis has been merged recently. the manifest is pushed into [config/deploy](./config/deploy)

**Comment by mazzy89** [comment]
We can close this
